export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER' ;

export const SIGNIN_START = 'SIGNIN_START' ;
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS' ;
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE' ;

export const CONFIRM_CODE_START = 'CONFIRM_CODE_START' ;
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS' ;
export const CONFIRM_CODE_FAILURE = 'CONFIRM_CODE_FAILURE' ;

export const CLEAR_REDUX_DATA =  'CLEAR_REDUX_DATA' ;
export const ADDRESS_SELECTED = 'ADDRESS_SELECTED';


export const ADD_ADDRESSS_SUCCESS = 'ADD_ADDRESSS_SUCCESS';

export const GET_ORDER_SUCCESS = ' GET_ORDER_SUCCESS';


export const GET_HOME_DATA_START = ' GET_HOME_DATA_START' ;
export const GET_HOME_DATA_SUCCESS = ' GET_HOME_DATA_SUCCESS' ;
export const GET_HOME_DATA_FAIL = 'GET_HOME_DATA_FAIL' ;


export const SET_CATS = 'SET_CATS' ;
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const CHILDREN_CATEGORIES_SUCCESS = 'CHILDREN_CATEGORIES_SUCCESS' ;


export const  APPEND_PRODUCTS  = 'APPEND_PRODUCTS' ;

export const SET_CATEGORY_PRODUCTS_PAGE = 'SET_CATEGORY_PRODUCTS_PAGE' ;

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS' ;

export const GET_CART_ITEMS = 'GET_CART_ITEMS' ;

export const  SUCCESS_ORDER = 'SUCCESS_ORDER' ; 

export const SET_ADDING_PRODUCT_TO_CART = 'SET_ADDING_PRODUCT_TO_CART' ;

export const ADD_PRODUCT_TOCART_ERROR = 'ADD_PRODUCT_TOCART_ERROR' ;

export const CLEAR_ADDING_PRODUCT_TO_CART = 'CLEAR_ADDING_PRODUCT_TO_CART' ;

export const UPDATE_CART_ITEM_IMMEDIATELY  = 'UPDATE_CART_ITEM_IMMEDIATELY' ;
export const SET_SEARCH_PRODUCTS_PAGE  = 'SET_SEARCH_PRODUCTS_PAGE' ;
export const APPEND_SEARCH_PRODUCTS  = 'APPEND_SEARCH_PRODUCTS' ;

export const START_LOADING = 'START_LOADING'  ;

export const STOP_LOADING = 'STOP_LOADING' ;



